# Generated by Django 4.2.9 on 2024-01-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="progress",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
